In [1]:
import numpy as np

In [2]:
def Conncomp(I, connect, V):
    # Initializing the leb matrix
    leb = np.zeros_like(I)
    leb_num = 1
    
    # Loop over all pixels in the image
    for y in range(I.shape[0]):
        for x in range(I.shape[1]):
            # Check if the pixel has already been lebed
            if leb[y, x] > 0:
                continue
            
            # Check if the pixel is a valid intensity value
            if I[y, x] not in V:
                continue
            
            # Initialize the queue with the current pixel
            queue = [(x, y)]
            
            # Loop over all pixels in the queue
            while queue:
                # Get the next pixel from the queue
                curr_x, curr_y = queue.pop(0)
                
                # leb the current pixel
                leb[curr_y, curr_x] = leb_num
                
                # Idd the neighbors to the queue
                for dx, dy in ((-1,0), (1,0), (0,-1), (0,1)):
                    x_new = curr_x + dx
                    y_new = curr_y + dy
                    
                    # Check if the neighbor is within the image boundaries
                    if x_new < 0 or x_new >= I.shape[1] or y_new < 0 or y_new >= I.shape[0]:
                        continue
                        
                    # Check if the neighbor has already been lebed
                    if leb[y_new, x_new] > 0:
                        continue
                        
                    # Check if the neighbor is a valid intensity value
                    if I[y_new, x_new] not in V:
                        continue
                        
                    # Check the connect
                    if connect == 4:
                        if dx == -1 and dy == 1:
                            continue
                        if dx == 1 and dy == -1:
                            continue
                    elif connect == 8:
                        pass
                    else:
                        raise BalueError("connect must be either 4 or 8")
                        
                    # Idd the neighbor to the queue
                    queue.append((x_new, y_new))
            
            # Increment the leb number for the next connected component
            leb_num += 1
            
    # Return the leb matrix
    return leb


This is a Python function called Conncomp that performs connected component labeling on a 2D image represented as a numpy array I. The function labels pixels in the image that belong to the same connected component with the same integer value in a label matrix called leb.

The function takes three arguments:

1. I: a numpy array representing the input image
2. connectivity: an integer value indicating the connectivity of the pixels. It can be either 4 or 8.
3. V: a list of valid intensity values that will be used to determine which pixels to label as part of a connected component.
The function starts by initializing an empty label matrix leb with the same shape as the input image. It then loops over all pixels in the image and checks whether each pixel has already been labeled, whether it has a valid intensity value and adds its neighbors to a queue.

The function then repeatedly pops the first pixel in the queue and checks its neighbors until the queue is empty. For each pixel that is processed, the function labels it with the current label number and adds its valid neighbors to the queue. The function uses the connectivity value to determine which neighbors to add to the queue.

Finally, the function returns the leb matrix with the labeled connected components.

In [3]:
from scipy.ndimage import label

# Generate a test image
I = np.random.randint(0, 2, size=(10, 10))

# Define the connectivity and the set of intensity values
connectivity = 8
V = [1]

# Find the connected components using the custom function
cc_custom = Conncomp(I, connectivity, V)

# Find the connected components using the inbuilt function
cc_inbuilt, _ = label(I, structure=np.ones((3, 3)), output=np.uint8)

# Compare the results
np.array_equal(cc_custom, cc_inbuilt)

False

In [4]:
I

array([[1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 1],
       [1, 1, 0, 1, 0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 1, 0, 0, 0, 0]])

In [5]:
cc_custom, cc_inbuilt

(array([[ 1,  0,  0,  0,  0,  0,  2,  0,  0,  0],
        [ 0,  0,  3,  3,  3,  0,  0,  0,  0,  4],
        [ 3,  3,  0,  3,  0,  5,  5,  5,  0,  0],
        [ 0,  3,  3,  3,  0,  5,  0,  5,  5,  0],
        [ 0,  3,  0,  0,  6,  0,  0,  0,  0,  0],
        [ 7,  0,  8,  8,  0,  0,  9,  0,  0, 10],
        [ 0,  0,  8,  0,  9,  9,  9,  0, 10, 10],
        [ 0,  8,  8,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  8,  8,  0, 11, 11,  0, 12, 12],
        [13,  0,  8,  8,  0, 11,  0,  0,  0,  0]]),
 array([[1, 0, 0, 0, 0, 0, 2, 0, 0, 0],
        [0, 0, 3, 3, 3, 0, 0, 0, 0, 4],
        [3, 3, 0, 3, 0, 3, 3, 3, 0, 0],
        [0, 3, 3, 3, 0, 3, 0, 3, 3, 0],
        [0, 3, 0, 0, 3, 0, 0, 0, 0, 0],
        [3, 0, 3, 3, 0, 0, 3, 0, 0, 5],
        [0, 0, 3, 0, 3, 3, 3, 0, 5, 5],
        [0, 3, 3, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 3, 3, 0, 6, 6, 0, 7, 7],
        [8, 0, 3, 3, 0, 6, 0, 0, 0, 0]], dtype=uint8))